spring.application.name=Feedback_Management_System

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/DBName 	//Database Name of PostgreSQL
spring.datasource.username=username 		// Username of PSQL
spring.datasource.password=password 		// Password of PSQL

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable open-in-view warning (good practice)
spring.jpa.open-in-view=false

#OAuth Configuration
# GOOGLE OAUTH
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# REQUIRED
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


#for GitHub
spring.security.oauth2.client.registration.github.client-id={github-client-id}
spring.security.oauth2.client.registration.github.client-secret={github-client-secret}